# Generated by Django 3.2.1 on 2024-02-17 20:46

from django.db import migrations, models
import restaurants.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='default_menu_item.jpg', upload_to=restaurants.models.MenuItem.get_upload_to_path_image),
        ),
    ]
