# Generated by Django 3.2.1 on 2024-02-18 21:42

from django.db import migrations, models
import restaurants.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_typeofcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofcategory',
            name='image',
            field=models.ImageField(default='default_type_of_category.avif', upload_to=restaurants.models.TypeOfCategory.get_upload_to_path_image),
        ),
    ]
