# Generated by Django 3.2.1 on 2024-02-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20240223_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemorder',
            name='observation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
