# Generated by Django 3.2.1 on 2024-03-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_menuitemorder_observation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuitemorder',
            unique_together=set(),
        ),
    ]
