# Generated by Django 5.0.3 on 2024-03-19 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_clientinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientinfo',
            old_name='gmail',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='clientinfo',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Order', to='order.clientinfo'),
        ),
    ]
