# Generated by Django 5.0.3 on 2024-03-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.PositiveSmallIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='pay_later',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waiting_waiter',
            field=models.BooleanField(default=False),
        ),
    ]
