# Generated by Django 5.0.3 on 2024-03-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_order_id_order_pay_later_order_waiting_waiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
