# Generated by Django 5.0.3 on 2024-03-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='decision_made',
            field=models.BooleanField(default=False),
        ),
    ]
